name: GHL Profilux to MQTT Bridge
version: "1.0.10"
slug: profiluxmqtt
description: Connects to Profilux and allows control using MQTT
url: "https://github.com/cjburchell/hassio-profiluxmqtt/master/profiluxmqtt"
startup: application
boot: auto
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map: 
  - config:rw
options:
    PROFILUX_HOST: ""
    MQTT_HOST: ""
    MQTT_USER: ""
    MQTT_PASSWORD: ""
schema:
    PROFILUX_HOST: str
    MQTT_HOST: str
    MQTT_USER: str
    MQTT_PASSWORD: str
#image: "ghcr.io/home-assistant/{arch}-addon-example"
image: "registry.gitlab.com/cjburchell/profiluxmqtt:1.0.10-1034644330"
