# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: GHL Profilux to MQTT Bridge
version: "1.0.10"
slug: profiluxmqtt
description: Connects to Profilux and allows control using MQTT
url: "https://github.com/cjburchell/hassio-profiluxmqtt/master/profiluxmqtt2"
startup: application
boot: auto
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
    PROFILUX_HOST: ""
    MQTT_HOST: ""
    MQTT_USER: ""
    MQTT_PASSWORD: ""
schema:
    PROFILUX_HOST: str
    MQTT_HOST: str
    MQTT_USER: str
    MQTT_PASSWORD: str
image: "ghcr.io/home-assistant/{arch}-addon-example"
